### ISSUE TITLE
PMIx v3.0.0 release checklist

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix#783]
## Build the Release
- [ ] Verify the major,minor,release,greek version numbers in `VERSION`
- [ ] Update the `c:r:a` shared library version number(s) in `VERSION` [per the GNU Libtool shared library version number rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html)
   - **NOTE:** It may be helpful to use a command like `git checkout BRANCH; git pull --rebase; git log --stat --topo-order --decorate TAG_FROM_PREVIOUS_RELEASE..HEAD` to examine the Git logs and see what has changed.
   - [ ] *IF RELEVANT:* If this is a new backwards-compatible release on a single branch (i.e., this is `vx.y.z` where `z>1`), you probably want to examine `git log --stat --no-merges last_release_tag..this_branch_name` to see what source code files have changed (which directly impacts how to increment the `c:r:a` values).
  - [ ] *IF RELEVANT:* If this is a new release series (e.g., `vx.y.0`), set `r` to 0 and increase `c` values by 10 compared to the first release in the prior series (i.e., `vx.(y-1).0` or `v(x-1).0.0`, as relevant).
  - [ ] *IF RELEVANT:* If this is a new backwards-compatible release series (i.e., `vx.y.0`, where `y>1`), set`a` values to 10 so that the shared libraries will be ABI compatible with the prior release series.
  - [ ] *IF RELEVANT:* If this is a new backwards-**IN**compatible release series (i.e., `vx.0.0`), set `a` values to 0 so that there is no possibility of users accidentally mixing shared library versions.
- [ ] Update all documentation files (especially including dates and version numbers), including:
  - [ ] `README`: all relevant updates, build options, etc.  Be sure to update the date near the top of the file.
  - [ ] `NEWS`: List all user-noticeable changes.  Similar to setting shared library versions (above): 
       - Pro tip: if this is a new release on a single branch (i.e., this is `vx.y.z` where `z>1`), you probably want to examine `git log --stat --no-merges last_release_tag..this_branch_name` to see what has changed.
       - Pro tip: if this is a new release series (i.e., this is `vx.y.0` where `y>1`, or this is `vx.0.0`), you will need to be more creative in examining the git logs because this release is on a different branch than the prior release (`vx.(y-1).z`).  Hence, `git log ... last_release_tag..this_branch_name` will not necessarily give you need.  You may need to merge what has changed on your branch with what has changed on the prior release branch, depending on when the prior release branched from this branch.  Read the **SPECIFYING RANGES** section `gitrevisions(7)` for more details.
  - [ ] `LICENSE`: Update the years in the copyright notices 
- [ ] Create a tag for the release, matching the version being released (ie, `git tag -a v3.0.1 <HASH>`).  Verify <HASH> points to the correct release point.  Push the tag for the release.
- [ ] Build the tarball

## Publish the release
- [ ] Update the web site blog announcing the release
  - [ ] Verify the live web site to ensure announcement is present
- [ ] Close the relevant Github milestone in `pmix/pmix`
- [ ] Send an email to the `pmix@googlegroups.com` mailing list announcing the release

## Prep for next release in series
- [ ] Re-target (change milestone) all still-open issues for the new release to the next major or minor release of PMIx as appropriate
- [ ] Ensure that new Github milestones exist in [GitHub](https://github.com/pmix/pmix/issues) for the next release
- [ ] Update the PMIx version number in `VERSION` to `<NEXT_VERSION>` and set `greek` to `a1`
- [ ] Open a duplicate of this issue for the next release in this series.
